### ISSUE TITLE
Questions of use.

### ISSUE THREAD

**Issue by yfhuang9977** [Tingliangstu/New-Version-Spectral-decomposition-python-tools#4]
Hi author, I have a NEMD program that I wrote myself, what atomic data do I need to output as an input file for this post-processing tool？

**Comment by Tingliangstu** [comment]
Hi, u can follow the example before using it in your case.

**Comment by chenghaosx** [comment]
Dear Dr. Liang Ting, first of all, thank you for publishing this project. I encountered some problems when trying to run the example. I ran "relax_thermal.in" through lammps to get "vels.dat", then compiled "compactify_vels.cpp" and added "compactify_vels.exe" to the path. At this time, I ran "SHC_generate.py". Initially, everything was normal, but it kept showing that "vels.compact.dat" was being generated and the generated file was very large (much more than 10GB). So I stopped generating the file and re-ran "SHC_generate.py" with the existing "vels.compact.dat" for calculation, prompting the warning "LAMMPS SETUP Warning: Number of atoms on left and right side don't match!" This may be because I did not completely generate the corresponding "vels.compact.dat" file. Apart from this, the program can run normally and output spectral thermal conductance diagrams.
So I am wondering whether I need to wait for the generation of "vels.compact.dat" or my operation process is wrong? (It is worth noting that I did not change any parameters in the example) The following is the output log of my running program and the final call part of the program.
Looking forward to your reply!
<img width="449" alt="微信图片_20240923171633" src="https://github.com/user-attachments/assets/d5bd04ee-32aa-47de-9628-9ab74a7204f6">
<img width="436" alt="微信图片_20240923171640" src="https://github.com/user-attachments/assets/ac4912aa-f314-48f3-9e72-3e89001d7c37">

**Comment by Tingliangstu** [comment]
1. What system are you running on? There may be some problems under Windows.
2. Whether the compressed file you want is larger than the original file?
3. The number of atoms at both ends of the interface need not be equal. This is a warning, not a mistake. In fact, the number of atoms at either end of the interface depends on what you define at the interface.

**Comment by chenghaosx** [comment]
Thank you very much for your reply! I did run the program under Windows and the compressed file "vels.compact.dat" is much larger than the original "vels.dat" file

**Comment by Tingliangstu** [comment]
You can use compactify_vels.cpp to compress the velocity file on linux, and then transfer the compressed file to Windows to continue the SHC calculation. compactify_vels.cpp may not be suitable for Windows. Good luck to you.

**Comment by chenghaosx** [comment]
Thank you for your reply! Following your suggestion, I tried to compress the speed file on the Ubuntu system. It worked successfully! Thanks again for your reply!

**Comment by Tingliangstu** [comment]
Done
